DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS INGREDIENT;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS RECIPE_INGREDIENT;
DROP TABLE IF EXISTS RECIPE_CATEGORY;

CREATE TABLE RECIPE(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   title TEXT NOT NULL,
   desc TEXT,
   fat INT,
   calories INT,
   protein INT,
   rating INT,
   sodium INT,
   ingredients TEXT NOT NULL,
   directions TEXT NOT NULL
);

CREATE TABLE CATEGORY(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT NOT NULL
);

CREATE TABLE RECIPE_CATEGORY(
   recipe_id INTEGER NOT NULL,
	category_id INTEGER NOT NULL,
	PRIMARY KEY (recipe_id, category_id),
	FOREIGN KEY (recipe_id) REFERENCES RECIPE (ID), 
	FOREIGN KEY (category_id) REFERENCES CATEGORY (ID)
);

CREATE TABLE INGREDIENT(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT NOT NULL
);

CREATE TABLE RECIPE_INGREDIENT(
   ingredient_id INTEGER NOT NULL,
   recipe_id INTEGER NOT NULL,
   PRIMARY KEY (recipe_id, ingredient_id),
   FOREIGN KEY (recipe_id) REFERENCES RECIPE (ID), 
	FOREIGN KEY (ingredient_id) REFERENCES INGREDIENT (ID)
);

CREATE TABLE INVENTORY(
   ingredient_id INTEGER NOT NULL,
   stock REAL DEFAULT 0,
   PRIMARY KEY (ingredient_id),
	FOREIGN KEY (ingredient_id) REFERENCES INGREDIENT (ID)
);