DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS INGREDIENT;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS RECIPE_INGREDIENT;
DROP TABLE IF EXISTS RECIPE_CATEGORY;
DROP TABLE IF EXISTS CONSUMPTION;

CREATE TABLE INGREDIENT(
   `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   `NAME` TEXT NOT NULL,
   `Stock` REAL NOT NULL DEFAULT 0,
   `BURNED` REAL NOT NULL DEFAULT 0
);

CREATE TABLE RECIPE(
   `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   `title` TEXT NOT NULL,
   `desc` TEXT,
   `fat` INTEGER,
   `calories` INTEGER,
   `protein` INTEGER,
   `rating` REAL NOT NULL DEFAULT 0,
   `sodium` INTEGER,
   `ingredients` TEXT NOT NULL,
   `directions` TEXT NOT NULL
);

CREATE TABLE RECIPE_INGREDIENT(
   recipe_id INTEGER NOT NULL,
   ingredient_id INTEGER NOT NULL,
   PRIMARY KEY (recipe_id, ingredient_id),
   FOREIGN KEY (recipe_id) REFERENCES RECIPE (ID) ON UPDATE NO ACTION ON DELETE CASCADE, 
   FOREIGN KEY (ingredient_id) REFERENCES INGREDIENT (ID) ON UPDATE NO ACTION ON DELETE CASCADE
);


CREATE TABLE CATEGORY(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT NOT NULL
);

CREATE TABLE RECIPE_CATEGORY(
   recipe_id INTEGER NOT NULL,
   category_id INTEGER NOT NULL,
   PRIMARY KEY (recipe_id, category_id),
   FOREIGN KEY (recipe_id) REFERENCES RECIPE (ID),
   FOREIGN KEY (category_id) REFERENCES CATEGORY (ID)
);

CREATE TABLE `CONSUMPTION`(
   `ingredient_id` INTEGER NOT NULL,
   `date` TEXT NOT NULL,
   `amount` REAL NOT NULL,
   PRIMARY KEY(`ingredient_id`, `date`),
   FOREIGN KEY(`ingredient_id`) REFERENCES `INGREDIENT`(`ID`)
      ON UPDATE NO ACTION ON DELETE CASCADE
)
